; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.21022.08 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
_bad_alloc_Message DQ FLAT:$SG20507
_DATA	ENDS
CONST	SEGMENT
$SG20507 DB	'bad allocation', 00H
CONST	ENDS
PUBLIC	_TI1J
PUBLIC	?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ	; AEGP_SuiteHandler::MissingSuiteError
PUBLIC	_CTA1J
PUBLIC	_CT??_R0J@84
PUBLIC	??_R0J@8					; long `RTTI Type Descriptor'
EXTRN	_CxxThrowException:PROC
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
pdata	SEGMENT
$pdata$?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ DD imagerel $LN3
	DD	imagerel $LN3+47
	DD	imagerel $unwind$?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ
pdata	ENDS
;	COMDAT ??_R0J@8
; File c:\users\brendan bolles\documents\development\proexr\src\aftereffects\fnord_missingsuiteerror.cpp
_DATA	SEGMENT
??_R0J@8 DQ	FLAT:??_7type_info@@6B@			; long `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.J', 00H
_DATA	ENDS
;	COMDAT _CT??_R0J@84
xdata$x	SEGMENT
_CT??_R0J@84 DD	01H
	DD	imagerel ??_R0J@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	04H
	DD	00H
xdata$x	ENDS
;	COMDAT _CTA1J
xdata$x	SEGMENT
_CTA1J	DD	01H
	DD	imagerel _CT??_R0J@84
xdata$x	ENDS
xdata	SEGMENT
$unwind$?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ DD 010901H
	DD	06209H
xdata	ENDS
;	COMDAT _TI1J
xdata$x	SEGMENT
_TI1J	DD	00H
	DD	00H
	DD	00H
	DD	imagerel _CTA1J
; Function compile flags: /Odtp
xdata$x	ENDS
_TEXT	SEGMENT
poop$ = 32
$T22094 = 36
this$ = 64
?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ PROC	; AEGP_SuiteHandler::MissingSuiteError

; 38   : {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 39   : 	//	Yes, we've read Scott Meyers, and know throwing
; 40   : 	//	a stack-based object can cause problems. Since
; 41   : 	//	the err is just a long, and since we aren't de-
; 42   : 	//	referencing it in any way, risk is mimimal.
; 43   : 
; 44   : 	//	As always, we expect those of you who use
; 45   : 	//	exception-based code to do a little less rudi-
; 46   : 	//	mentary job of it than we are here. 
; 47   : 	
; 48   : 	//	Also, excuse the Madagascar-inspired monkey 
; 49   : 	//	joke; couldn't resist. 
; 50   : 	//								-bbb 10/10/05
; 51   : 	
; 52   : 	PF_Err poop = PF_Err_BAD_CALLBACK_PARAM;

	mov	DWORD PTR poop$[rsp], 516		; 00000204H

; 53   : 
; 54   : 	throw poop;

	mov	eax, DWORD PTR poop$[rsp]
	mov	DWORD PTR $T22094[rsp], eax
	lea	rdx, OFFSET FLAT:_TI1J
	lea	rcx, QWORD PTR $T22094[rsp]
	call	_CxxThrowException
$LN2@MissingSui:

; 55   : }

	add	rsp, 56					; 00000038H
	ret	0
?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ ENDP	; AEGP_SuiteHandler::MissingSuiteError
_TEXT	ENDS
END
